import Head from "next/head";
import Footer from "@/components/footer/Footer";
import Script from "next/script";
import Link from "next/link";
import { CountUp } from "use-count-up";

var $ = require("jquery");
if (typeof window !== "undefined") {
  window.$ = window.jQuery = require("jquery");
}

import "owl.carousel/dist/assets/owl.carousel.css";
import "owl.carousel/dist/assets/owl.theme.default.css";

import dynamic from "next/dynamic";
import Header from "@/components/header/Header";
import React, { useEffect, useState } from "react";
const OwlCarousel = dynamic(() => import("react-owl-carousel"), {
  ssr: false,
});

export default function Home() {
  // useEffect(() => {
  //   const sidebar = document.querySelector("#sidebar");
  //   const sidebarToggler = document.querySelector(".sidebar_toggler");

  //   const handleSidebarToggle = () => {
  //     sidebar.classList.toggle("show");
  //   };

  //   const handleOutsideClick = (e) => {
  //     if (
  //       e.target.id !== "sidebar" &&
  //       e.target.className !== "sidebar_toggler"
  //     ) {
  //       sidebar.classList.remove("show");
  //     }
  //   };

  //   sidebarToggler.addEventListener("click", handleSidebarToggle);
  //   window.addEventListener("click", handleOutsideClick);

  //   return () => {
  //     sidebarToggler.removeEventListener("click", handleSidebarToggle);
  //     window.removeEventListener("click", handleOutsideClick);
  //   };
  // }, []);

  return (
    <>
      <div>
        <Head>
          <title> Agreement paper </title>
          <meta charSet="utf-8"></meta>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
      </div>

      <div className="header">
        <Header />
        <div className="container">
          <div className="row header_bio">
            <div className="col-12 col-lg-6">
              <div className="head_details">
                <h2>
                  Dedicated Volunteer network to get paid for good work
                </h2>
                <p>
                </p>
                {/* <Link href="/book-a-demo" className="a_list_noSty">
                  <button>Get a Demo today</button>
                </Link> */}

                <div className="_demoBtn">
                  <Link href="/book-a-demo" className="headB">
                    <span>Get a Demo today</span>
                  </Link>
                </div>
              </div>
            </div>
            <div className="col-12 col-lg-6 laptop">
              <img src="image/laptop_img.png" alt="Generative AI Contract Management" />
            </div>

            <div className="col-12 col-lg-6 full_laptop">
              <img className="" src="image/laptop_full.png" alt="Contract Management Solution
" />
            </div>
          </div>
        </div>

        

       

        <section className="anvGallerBox ">
          <div
            className="grtInner_head"
            data-aos="fade-up"
            data-aos-duration="2000"
          >
            {/* <h1> Dedicated Volunteer network to get paid for good work </h1> */}
            <h5 className="mt-2">
              We celebrate diversity and promote inclusion! We belive that every
              person brings unique experiences , perspectives and skills to the
              table , and we are commited to creating a workplace that values
              and respects everyone.
            </h5>

            <div className="grid-wrapper mt-3">
              <div className="big">
                <img src="image/volunteer1.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer2.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer3.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer5.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer6.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer7.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer8.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer9.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer10.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer11.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer12.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer13.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer14.jpg" alt="img" />
              </div>
            </div>

            {/* <div className="grid-wrapper mt-3">
              <div>
                <img src="image/volunteer1.jpg" alt="img" />
              </div>
              <div>
                <img src="image/volunteer2.jpg" alt="img" />
              </div>
              <div className="tall">
                <img src="image/volunteer3.jpg" alt="img" />
              </div>
              <div className="wide">
                <img src="image/volunteer1.jpg" alt="img" />
              </div>
              <div>
                <img src="image/volunteer5.jpg" alt="img" />
              </div>
              <div className="tall">
                <img src="image/volunteer6.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer2.jpg" alt="img" />
              </div>
              <div>
                <img src="image/volunteer1.jpg" alt="img" />
              </div>
              <div className="wide">
                <img src="image/volunteer2.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer7.jpg" alt="img" />
              </div>
              <div className="tall">
                <img src="image/volunteer5.jpg" alt="img" />
              </div>
              <div>
                <img src="image/volunteer6.jpg" alt="img" />
              </div>
              <div>
                <img src="image/volunteer7.jpg" alt="img" />
              </div>
              <div>
                <img src="image/volunteer3.jpg" alt="img" />
              </div>
              <div>
                <img src="image/volunteer5.jpg" alt="img" />
              </div>
              <div className="big">
                <img src="image/volunteer1.jpg" alt="img" />
              </div>
              <div className="wide">
                <img src="image/volunteer2.jpg" alt="img" />
              </div>
            </div> */}
          </div>
        </section>

        <Footer />
      </div>

      <Script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"
      ></Script>
    </>
  );
}
